.circleci/config.yml
README.md
codecov.yml
jest.config.js
package.json

Setup CodeCov check using CircleCI Orb.

feat: codecov setup

---

README.md
controllers/comments.js
controllers/utils/__tests__/functions.test.js
controllers/utils/functions.js
package.json
services/comments.js
services/utils/__tests__/functions.test.js
services/utils/error.js
services/utils/functions.js

Provides support for user context requested in #19

feat: context user support

---

README.md
package.json
services/utils/__tests__/functions.test.js
services/utils/functions.js

- introduces support for bad words plugin customization (#31)

feat: bad words customization

---

controllers/comments.js
package.json
services/comments.js

- introduce query parameters support ( #25 #29 )
- introduce email validation for non-strapi users ( #29 )
- fix the 500 error while fetching comments in version `v1.0.1-beta.3`

feat: support for query parameters

---

models/comment.settings.json
models/report.settings.json

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/56
Add visibility control for collections from plugin

Feature: Add visibility control for collections

---

config/routes.json
config/schema.graphql.js
controllers/comments.js
services/comments.js

https://github.com/VirtusLab/strapi-plugin-comments/issues/54

feature: add gql support

---

README.md

> https://github.com/VirtusLab/strapi-plugin-comments/issues/63
> This PR will add delete comment API request on documentation.
> API request has been tested on Postman.

add delete comment API request

---

admin/src/utils/index.js

https://github.com/VirtusLab/strapi-plugin-comments/issues/-<your-ticket-#>

fix: Issue #96

---

README.md

https://github.com/VirtusLab/strapi-plugin-comments/issues/-<your-ticket-#>

docs: fixed missing slug for delete comment

---

README.md

No tickets. 
Fix typos and remove duplicates from docs. 
No test needed.

Fix typo and remove duplicates from README file

---

.circleci/config.yml
server/services/client.ts
server/services/common.ts
types/services.d.ts
yarn.lock

NA
Fixed all query params by wrapping them in objects. 
Fixed minor spelling error. 
Improved type of params in CommonService.FindOne()
- Test `POST` request to `/:relation`

fix: wrapped where param in db query

---

admin/src/pages/Discover/utils/filtersSchema.ts
admin/src/pages/Reports/utils/filtersSchema.ts

[#20rfmyr](https://app.clickup.com/t/20rfmyr)
Adding basic filter options for both Discover and Reports pages

feat: basic filters options added to Discover and Reports

---

server/services/admin.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/174
Relates to: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/146
Strapi core changed in the way that down the line `populate` is being checked if it has a `count` field. Without checking if `populate` field is an object. 🤷‍♂️ 
For `boolean` this works just fine. But if `populate` key is present at all it's value is used as-is.
Comments list should be readable without any issues.

fix: author population

---

README.md
admin/src/components/AdminAvatar/index.tsx
admin/src/components/AdminAvatar/styles.ts
admin/src/components/DiscussionThreadItem/index.tsx
admin/src/components/DiscussionThreadItem/styles.ts
admin/src/components/DiscussionThreadItemActions/index.tsx
admin/src/components/DiscussionThreadItemFooter/index.tsx
admin/src/components/ModeratorResponse/index.tsx
admin/src/components/PreviewWysiwyg/utils/satinizeHtml.ts
admin/src/components/Wysiwyg/Editor.tsx
admin/src/components/Wysiwyg/WysiwygNav.tsx
admin/src/components/Wysiwyg/WysiwygStyles.ts
admin/src/pages/Details/index.tsx
admin/src/pages/Discover/components/DiscoverTableRow/index.tsx
admin/src/translations/en.json
package.json

https://github.com/VirtusLab/strapi-plugin-comments/issues/187
Solves issue with `Drilldown` if we've got admin responses only in the thread.
1. Run the app
2. Create a threads directly from Moderation panel
3. See that all is working as well as custom formatting (bold, italic, underline)

[CU-862j5xat0] fix: drilldown fail

---

README.md
package.json
server/src/controllers/__tests__/client.controller.test.ts
server/src/controllers/client.controller.ts
server/src/services/__tests__/client.service.test.ts
server/src/services/client.service.ts
server/src/services/common.service.ts
server/src/validators/api/controllers/client.controller.validator.ts
yarn.lock

https://github.com/VirtusLab/strapi-plugin-comments/issues/281
Allows creating comments non-strapi users and author validations on update process

fix/281: allows creating comments non-strapi users

---

admin/src/api/schemas.ts
admin/src/components/CommentRow/index.tsx
server/src/services/__tests__/admin.service.test.ts
server/src/services/admin/admin.service.ts
server/src/services/admin/utils.ts
server/src/services/common.service.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/286

fix/286: problem with long comments

---

server/src/services/client.service.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/291

fix/291: set locale to null on fetch thread data if not provided

---

server/src/bootstrap.ts
server/src/repositories/comment.repository.ts
server/src/services/common.service.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/290

fix/290: remove all comments after remove the source entry

---

package.json
yarn.lock

Optimize the package size and build minification ON.
N/A

fix: package size optimization

---

server/src/services/__tests__/common.service.test.ts
server/src/services/common.service.ts
server/src/validators/api/controllers/client.controller.validator.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/295

fix: 295 allow filtering comments by approval status

---

README.md
admin/src/components/ModeratorResponseModal/index.tsx
admin/src/pages/Details/ModeratorResponse.tsx
admin/src/pages/Settings/index.tsx
package.json
yarn.lock

https://github.com/VirtusLab/strapi-plugin-comments/issues/298
Updates the dependencies causing blank page.

fix: issue #298, blank pages

---

server/src/@types/controllers.ts
server/src/graphql/getResolversConfig.ts
server/src/services/__tests__/client.service.test.ts
server/src/services/client.service.ts
yarn.lock

https://github.com/VirtusLab/strapi-plugin-comments/issues/300
- fix authors error while adding a comment with JWT authentication.

fix: fix authors while using auth

---

admin/src/api/schemas.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/317

fix/317: fix schema on FE
