README.md
config/routes.json
controllers/comments.js
models/comment.settings.json
package.json
services/comments.js

Introducing the relation slug to be able to search by it, instead of sync searching with lodash.
Fix: Issue #2 
1. Add comment with proper relation
2. See that relation is still visible in moderation mode & in the endpoint payload

fix: issue #2 search by relation slug

---

controllers/comments.js
package.json

Fixes Issue #15 with uuid parsing

fix: issue #15 uuid parsing in mongo

---

package.json
services/comments.js

- Based on comment in #25, filters & query are now applied only to the root level of comments.

fix: filtering only root level

---

.github/pull_request_template.md
README.md
config/functions/bootstrap.js
package.json

https://github.com/VirtusLab/strapi-plugin-comments/issues/49
Changes bootstrap method to be compatible with `Strapi 3.6.x`
N/A

fix: compatibility with strapi 3.6.x

---

README.md
services/utils/__tests__/functions.test.js
services/utils/functions.js

Changes misleading naming of the config file from "custom.js" to "plugins.js". 
- Install plugin to strapi project.
- Add configuration
- Check if the configuration is being applied

refactor: change config file name

---

config/schema.graphql.js

https://github.com/VirtusLab/strapi-plugin-comments/issues/81
Removed unnecessary and not working JSON parsing from graphql schema.
Tested on local strapi installation with graphql playground.

fix: graphql unnecessary json parsing

---

README.md
services/comments.js

https://github.com/VirtusLab/strapi-plugin-comments/issues/6
This PR implements feature of sending email notifications about abuse reports to moderators. 
- Created new Strapi project
- Configured email provider for Strapi email plugin
- Added and configured comments plugin 
- Created moderator user and provided his role in plugin config
- Created a new comment and a new abuse report about this comment

feat: report email notification

---

config/schema.graphql.js

Fixes https://github.com/VirtusLab/strapi-plugin-comments/issues/85
Adds `created_at`, `created_by`, `updated_at` and `updated_by` fields to base Comments schema so they are available to query when fetching comments

Adds missing fields from Comments schema

---

__mocks__/initSetup.ts
admin/src/components/Avatar/index.tsx
admin/src/components/DiscussionThreadItemFooter/index.tsx
admin/src/pages/Discover/components/DiscoverTableRow/index.tsx
package.json
server/controllers/utils/parsers.ts
server/services/__tests__/common.test.ts
server/services/admin.ts
server/services/client.ts
server/services/common.ts
server/services/utils/functions.ts
types/contentTypes.ts
types/services.d.ts
yarn.lock

https://github.com/VirtusLab/strapi-plugin-comments/issues/113
Provides ability to populate author field and all fields related to it.
> Note
> PR #132 must be merged first
1. Run application
2. Add couple comments using Strapi Users (Authenticated)
3. Try to call REST API as 
`api/comments/api::page.page:1/flat?populate[author][populate][0]=role`
4. See that `role` is part of the `author` per each comment
1. Run application
2. Provide an `avatar` field to the `User` Collection and set it for your test users
3. Add couple comments using Strapi Users (Authenticated)
3. Try to call REST API as 
`api/comments/api::page.page:1/flat?populate[author][populate][0]=role&populate[author][populate][1]=avatar`
4. See that `role` is part of the `author` per each comment …

[CU-2cq60k0] feat: issue #113 author field population

---

admin/src/components/DiscussionThreadItemFooter/index.tsx
admin/src/pages/Discover/components/DiscoverTableRow/index.tsx
admin/src/translations/en.json
admin/src/translations/fr.json
admin/src/translations/pt-BR.json
package.json

https://github.com/VirtusLab/strapi-plugin-comments/issues/137
Covers case when Strapi User was removed and still got some comments assigned. Prevents interface crashes.
1. Create Strapi User
2. Add comment associated to newly created user
3. Remove user
4. See that `Author removed` is visible instead of name and interface is not crashing

CU-2dz37t8 - issue 137 - comments are broken if user was deleted

---

jest.config.ts
server/controllers/utils/__tests__/functions.test.js
server/controllers/utils/__tests__/parsers.test.js
server/controllers/utils/parsers.ts
server/graphql/queries/findAllInHierarchy.ts
server/services/graphql.ts
server/services/utils/__tests__/functions.test.js

https://app.clickup.com/30978717/v/b/xhcmx-63
- Server side handling of filtering by parameters that can be found in newly added `comments` custom field
- tests expand
- including JS test suites
- fixes for failing tests
Perform calls like:
- http://localhost:1337/api/comments/api::page.page:5/flat?filterBy=DATE_CREATED&filterByValue=2022-10-12T13:21:13.595Z
- http://localhost:1337/api/comments/api::page.page:5/flat?filterBy=APPROVAL_STATUS&filterByValue=APPROVED

feat: custom fields on server-side [CU-xhcmx-63]

---

admin/src/custom-fields/comments/components/input/consts.ts
admin/src/custom-fields/comments/components/input/input.tsx
admin/src/custom-fields/comments/components/input/utils.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/175
This PR fixes error happening when custom field is added to already existing entity.
1. Create a content type
2. Create content type's item
3. Add comments custom field
4. Edit existing item
5. No error should be presented
6. Warning should be present in browser's console

fix: custom field on existing entity

---

README.md
admin/src/index.ts
admin/src/translations/index.ts
admin/src/utils/getMessage.ts
package.json

https://github.com/VirtusLab/strapi-plugin-comments/issues/180
Solves failure for `async` loading of translations. Method has been changed to synchronous.
1. Run the app
2. See that translations are loading properly

fix: [CU-862hz23aa] Translations init failure while async loading

---

README.md
admin/src/components/Avatar/index.tsx
admin/src/pages/Settings/index.tsx
admin/src/translations/en.json
server/config/index.ts
server/services/__tests__/common.test.ts
server/services/admin.ts
server/services/client.ts
server/services/common.ts
server/services/utils/functions.ts
server/utils/constants.ts
types/config.d.ts
types/services.d.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/183
- removing selected fields from author object in the response by config
- minor UI issue
- set `blockedAuthorProps` in config
- query for comments
- blocked props should be blocked

feat: author entity props blocking

---

admin/src/pages/Settings/index.tsx
server/services/common.ts
types/services.d.ts

[https://github.com/VirtusLab/strapi-plugin-comments/issues/-<your-ticket-#>](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/190)
- disable filtering of author entities for admin panel
- ", " changed to "," in admin's panel comments settings page
- all author props are available for admins
- in settings page just "," can be used as items delimiter

fix: author blocked props

---

README.md
admin/src/index.ts
server/controllers/client.ts
server/graphql/queries/findAllPerAuthor.ts
server/graphql/queries/index.ts
server/graphql/types/comment-author-type.ts
server/graphql/types/index.ts
server/graphql/types/response-find-all-per-author.ts
server/routes/client.ts
server/services/__tests__/common.test.ts
server/services/common.ts
server/services/utils/__tests__/parsers.test.js
server/services/utils/functions.ts
server/services/utils/parsers.ts
server/utils/constants.ts
types/controllers.d.ts
types/services.d.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/209
Provides ability to filter by `author` for generic & strapi users
- `/api/comments/author/:id` - Strapi users
- `/api/comments/author/:id/generic` - Generic users
1. Run you projects with some comments created
2. Run queries against endpoints:
- `/api/comments/author/:id` - Strapi users
- `/api/comments/author/:id/generic` - Generic users
3. You should get comments authored by specific user with `related` entity attached

feat(api): issue #209 - find all by author

---

server/services/client.ts
server/services/common.ts

All collection types should allow comments when no enabled collection types are set.
Configuration Page
This PR fixes the behavior of the "Enable comments only for" setting in the Comments plugin configuration. The tooltip underneath the setting states that "If none is selected, all the content types are enabled" however, in production when no content types are selected then no content types are enabled. 
This fix was tested with two Content Types: Post and Writer. 
Before Fix: 
1. Enable no content types
2. Try to add comment to Post - Does not Comment
3. Try to add comment to Writer - Does not Comment
4. Enable Post in settings
5. Try to add comment on Post - Correctly adds comment
6. Try to add comment on Writer - Correctly does not add comment
After Fix: 
1. Enable no content types
2. …

Fixed behavior when no enabled collections are configured.

---

.circleci/config.yml
package.json
yarn.lock

https://github.com/VirtusLab/strapi-plugin-comments/issues/228
Fixes build issues because of packages misalignment with Strapi `4.13.x`
N/A

fix: strapi 4.13 packages alignment

---

README.md
content-types/index.ts
package.json
server/services/__tests__/common.test.ts
server/services/common.ts
server/utils/__tests__/functions.test.ts
server/utils/constants.ts
server/utils/functions.ts
server/utils/types.ts
types/services.d.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/202
- adding lifecycle hooks to comments content types
- register lifecycle hooks (see README.md)
- start a server
- trigger lifecycle action (`afterCreate` for example)
- observe results
- lifecycle event should be triggered

feat: lifecycle hooks

---

README.md
package.json
server/controllers/client.ts
server/controllers/utils/parsers.ts
server/services/__tests__/common.test.ts
server/services/admin.ts
server/services/common.ts
types/controllers.d.ts
types/services.d.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/239
- fields of comment entity can be skipped
- start the server
- make a API call like `http://localhost:1337/api/comments/<id>?omit[]=blocked&omit[]=related&omit[]=author`
- response should not contain specified fields

feat: CU-86934hnmg rest api skipping fields

---

admin/src/pages/Discover/components/DiscoverTableRow/index.tsx

No ticket 
current link on entry looks like this 
http://localhost:1337/admin/content-manager/collectionType/api::game.game/44
http://localhost:1337/admin/content-manager/collection-types/api::game.game/44
actual link in admin 
strapi version 4.25.8
comment plugin version  2.3.2
I didn't test it< but I see how it works in admin

fix: fixed link to entry on discover page

---

admin/src/components/CommentRow/index.tsx
admin/src/components/DiscussionThreadItem/DiscussionThreadItemActions.tsx
admin/src/components/DiscussionThreadItem/DiscussionThreadItemFooter.tsx
admin/src/components/IconButtonGroup/index.tsx
admin/src/components/ModeratorResponseModal/index.tsx
admin/src/components/UserAvatar/AdminAvatar.tsx
package.json
server/src/services/__tests__/common.service.test.ts
server/src/services/admin/admin.service.ts
server/src/services/common.service.ts
server/src/validators/utils.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/283
https://github.com/VirtusLab/strapi-plugin-comments/issues/265
1. Fixes the rare behavior of Admin UI when comments are not displayed
2. Adds the email tooltip in the Admin UI if author is not and admin
1. Run the app and see that comments are visible on the "Discovery" page
2. See that while hovering author, the email is showing

fix: admin panel does not display comments #283

---

server/src/bootstrap.ts
server/src/validators/api/controllers/client.controller.validator.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/322
Add isAdminComment to the filters

fix/322: add `isAdminComment` to the filters

---

admin/src/api/schemas.ts
server/src/repositories/__tests__/store.repository.test.ts
server/src/repositories/store.repository.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/317
After verification on the settings page, we can't set up report reasons, so we should always read from the local config - not from the store, because the user can't edit it.

fix/317: read report reasons from local config

---

admin/src/components/ApproveFlow/index.tsx
admin/src/components/SideNav/index.tsx
admin/src/components/Wysiwyg/WysiwygNav.tsx
package.json

https://github.com/VirtusLab/strapi-plugin-comments/issues/332
- change `ariaLabel` props to `aria-label` in SideNavbar so it is rendered correctly in the DOM
- add `getMessage` to lacking imports after merging translations

fix: aria-label in side navbar

---

package.json
server/src/controllers/__tests__/client.controller.test.ts
server/src/controllers/__tests__/utils/parser.test.ts
server/src/controllers/utils/parsers.ts
server/src/services/__tests__/client.service.test.ts
server/src/services/__tests__/common.service.test.ts
server/src/services/client.service.ts
server/src/services/common.service.ts
server/src/services/utils/functions.ts
server/src/validators/repositories/comment.schema.ts

https://github.com/VirtusLab/strapi-plugin-comments/issues/333
PR ensures that Strapi users are related to the User collection from `plugin::users-permissions.user`. This way, the username, email, and avatar should be connected to the User data, and in the case of an update, they should be populated in the comment data.
- Test all endpoints for the Strapi and Non-Strapi users, see if Avatars are populated correctly.

fix: Strapi user relations
